CREATE TABLE TB_CLIENT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);

CREATE TABLE TB_PRODUCT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100),
    PRICE NUMERIC(20, 2)
);

CREATE TABLE TB_ORDER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER REFERENCES TB_CLIENT (ID),
    DATE_ORDER TIMESTAMP,
    TOTAL NUMERIC (20, 2)
);


CREATE TABLE TB_ORDER_ITEM (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INTEGER REFERENCES TB_ORDER (ID),
    PRODUCT_ID INTEGER REFERENCES TB_PRODUCT (ID),
    QUANTITY INTEGER
);


